### ISSUE TITLE
Use Case Model Document

### ISSUE THREAD

**Issue by ForrestSwift** [SpencerM0415/FiveGuys_420Project#16]

**Comment by peterclukey** [comment]
[FiveGuys_Deliverable_2_UseCaseModels.pdf](https://github.com/SpencerM0415/FiveGuys_420Project/files/6097881/FiveGuys_Deliverable_2_UseCaseModels.pdf)

**Comment by peterclukey** [comment]
Use case model document created

**Comment by peterclukey** [comment]
[FiveGuys_Deliverable_2_UseCaseModels.pdf](https://github.com/SpencerM0415/FiveGuys_420Project/files/6103013/FiveGuys_Deliverable_2_UseCaseModels.pdf)

**Comment by peterclukey** [comment]
Use case models v2
