### ISSUE TITLE
Board Prototype

### ISSUE THREAD

**Issue by ForrestSwift** [SpencerM0415/FiveGuys_420Project#22]
Create a working prototype of the board that can list pieces in text format - TDHC is Tall Dark Hollow Circle or SLSS is Short Light Solid Square is an example format but anything works. Allow pieces to be chosen and placed on a 4x4 grid. Output remaining pieces as well as board to console.

**Comment by AustinL0214** [comment]
Decided to use Java for the prototype. Everyone has knowledge in the programming language. First prototype will be primarily text/console outputs

**Comment by AustinL0214** [comment]
Switched to Unity for board prototype. Creating board, sprites, and simple mechanics.
