### ISSUE TITLE
Daily Scrum 3/25

### ISSUE THREAD

**Issue by SpencerM0415** [SpencerM0415/FiveGuys_420Project#34]

**Comment by SpencerM0415** [comment]
As Product Owner, I am:

- Managing Product Backlog

- Updating ZenHub Board

- Assisting in Software Development 

- Pushing Documents to GitHub

**Comment by peterclukey** [comment]
As Scrum Master:
Updating and managing scrum.

Assisting with documents as required

managing Sprint Backlog

**Comment by ForrestSwift** [comment]
This week I am working on:
- Updating the Sprint Backlog
- Creating 3 Analysis Sequence Diagrams and 1 Design Sequence Diagram
- Updating SRS

**Comment by AustinL0214** [comment]
This week I am working on

- Creating 3 Analysis Sequence Diagrams ans 1 Design Sequence Diagram
- Continuing Software Development
- Updating README File

**Comment by Alex-Landry** [comment]
This week i will be doing some sequence diagrams as well as some software development.
