### ISSUE TITLE
Weekly Scrum

### ISSUE THREAD

**Issue by ForrestSwift** [SpencerM0415/FiveGuys_420Project#50]

**Comment by AustinL0214** [comment]
Finishing win conditions for game. Updating config management document. Fixing a few bugs with drag and drop then hopefully getting to turn-based game play.

**Comment by ForrestSwift** [comment]
This week as Scrum Master I worked on:
- Updating Sequence Diagrams
- Updating Domain Model
- Updating Focus Group Doc
- Writing the Sprint Review
- Managing Github/Kanban

**Comment by Alex-Landry** [comment]
This week I did the detailed design document

**Comment by SpencerM0415** [comment]
- Creating Architecture Design Document
- Developing code for the game

**Comment by peterclukey** [comment]
* Acted as Product Owner this sprint
* Updated Sprint Backlog
* Updated Product Backlog
* Worked on Design Doc
